######################################################################
# Automatically generated by qmake (3.0) Thu Oct 24 18:13:42 2013
######################################################################

TEMPLATE = app
TARGET = roadprj
INCLUDEPATH += .

# Input
HEADERS += constant.h dummy.h ffind.h processor.h types.h exp/ffind.h
SOURCES += dummy.cpp ffind.cpp main.cpp processor.cpp test.cpp exp/ffind.c
